export enum NotiType {
  POST_REACTION = 'POST_REACTION',
  COMMENT_POST = 'COMMENT_POST',
  COMMENT_REACTION = 'COMMENT_REACTION',
  REPLY_COMMENT = 'REPLY_COMMENT',
  NEW_FRIEND_REQUEST = 'NEW_FRIEND_REQUEST',
  FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
}

export enum NotiSenderType {
  USER = 'USER',
}
