export enum NotiType {
  POST_REACTION = 'POST_REACTION',
  COMMENT_POST = 'COMMENT_POST',
  COMMENT_REACTION = 'COMMENT_REACTION',
  REPLY_COMMENT = 'REPLY_COMMENT',
}

export enum NotiSenderType {
  USER = 'USER',
}
